name: exhibition_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.14
  - numpy=2.5.2
  - pandas=3.0.5
  - streamlit=1.62.0
  - pip
  - pip:
    - plotly==7.0.0
    - yfinance==1.7.0
    - pytrends==4.9.2